config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
 
  get 'subscriptions/index'
  get 'subscriptions/new'
  get 'subscriptions/edit'

  get '/about-us', to: 'home#about_us'
  get '/contact', to: 'home#contact'
  get '/meet-our-team', to: 'home#meet_our_team'

  resources :subscriptions, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :edit, :update]

  get '/signup', to: 'users#new'
  get '/users/:user_id', to: 'home#index_logged_in', as: 'user_profile'

  get '/recent_reminders', to: 'reminders#recent_reminders', as: 'recent_reminders'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
   has_many :user_subscription_bridge
   has_many :subscriptions, through: :user_subscription_bridge
   has_many :reminders
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :password, presence: true, confirmation: true, on: :create

  
  
    has_secure_password

    private

  def password_match
    errors.add(:password, 'Passwords do not match') if password != password_confirmation
  end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create]
    before_action :set_user, only: [:edit, :update]

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id # Log in the user upon successful signup
        redirect_to user_profile_path(@user)
      else
        if @user.errors[:password].include?("is too short (minimum is 6 characters)")
          flash[:error] = "Password must be at least 6 characters long."
        end
        render 'new'
      end
    end

    def edit
      # @user is already set by the before_action
    end

  def update
    @user = current_user

    if user_params[:current_password].present?
      unless @user.authenticate(user_params[:current_password])
        flash[:alert] = "Current password is incorrect."
        return render 'edit'
      end

      if user_params[:new_password].present? && user_params[:new_password].length >= 6
        @user.password = user_params[:new_password]
        @user.password_confirmation = user_params[:new_password]
        flash[:notice] = "Password updated successfully."
        return render 'edit'
      else
        flash[:alert] = "New password must be at least 6 characters long."
        return render 'edit'
      end
    end

    if user_params[:first_name].present? || user_params[:last_name].present?
      if @user.update(user_params.slice(:first_name, :last_name))
        flash[:notice] = "Profile updated successfully."
      else
        flash[:alert] = "Failed to update profile: " + @user.errors.full_messages.join(', ')
      end
    end

    if user_params[:current_password].blank? && user_params[:first_name].blank? && user_params[:last_name].blank?
      flash[:alert] = "No changes were made."
      return render 'edit'
    end

    redirect_to user_profile_path(@user)
  end

  
  
  
  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :current_password, :new_password, :password, :password_confirmation)
  end

  def require_login
    unless current_user
      redirect_to new_user_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
  <div class="container" style="background-image: url('/assets/bckg8.jpg'); background-size: cover; background-repeat: no-repeat; background-attachment: fixed;">
    <h1 class="heading">Edit Your Profile</h1>
    <div class="edit-profile-form">
      <%= form_for(@user, url: user_path(@user), method: :patch) do |f| %>
        <div class="form-group">
          <div class="form-floating">
            <%= f.text_field :first_name, class: "form-control custom", placeholder: "" %>
            <%= f.label :first_name, class: "form-label" %>
          </div>
        </div>
        <br>
        <div class="form-group">
          <div class="form-floating">
            <%= f.text_field :last_name, class: "form-control custom", placeholder: "" %>
            <%= f.label :last_name, class: "form-label" %>
          </div>
        </div>
        <br>
        <div class="form-group">
          <div class="form-floating">
            <%= f.password_field :current_password, class: "form-control custom", placeholder: "" %>
            <%= f.label :current_password, class: "form-label" %>
          </div>
        </div>
        <br>
        <div class="form-group">
          <div class="form-floating">
            <%= f.password_field :new_password, class: "form-control custom", placeholder: "" %>
            <%= f.label :new_password, class: "form-label" %>
          </div>
        </div>
        <br>
        <div class="edit-actions">
          <%= f.submit "Update", class: "btn btn-outline-primary accent-color" %>
          <a href="<%= user_profile_path(current_user) %>" class="btn btn-outline-danger accent-color" id="cancel-button">Cancel</a>
        </div>
      <% end %>
    </div>

    <div class="flash">
      <% if flash[:notice].present? %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
    
      <% if flash[:alert].present? %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <script>
    // Function to automatically hide the alerts after 5 seconds
    function hideAlerts() {
      const alerts = document.querySelectorAll('.alert');
      alerts.forEach((alert) => {
        setTimeout(function () {
          alert.style.display = 'none';
        }, 5000); // 5000 milliseconds (5 seconds)
      });
    }

    // Call the hideAlerts function when the page loads
    window.addEventListener('load', hideAlerts);
  </script>

  </div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user, url: users_path, html: { class: "form background-color" } do |f| %>
  <nav class="top-nav-bar">
    <%= link_to(root_path) do %>
      <%= image_tag('RecurrEx-logo.png', alt: 'Recurrex Logo', class: 'logo-image') %>
    <% end %>
    <div class="top-nav-links">
    <%= link_to 'Login', login_path, class: 'btn btn-outline-primary accent-color'%>
    </div>
</nav>

<div class="container" style="background-image: url('/assets/bckg1.jpg'); background-size: cover; background-repeat: no-repeat; background-attachment: fixed;">
  <div class="edit-profile-form">
    <h1>Sign Up</h1>
    <br>
    <div class="form-group">
      <div class="form-floating">
        <%= f.text_field :first_name, class: "form-control custom", placeholder: "", required: "true" %>
        <%= f.label :first_name, class: "form-label" %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <div class="form-floating">
        <%= f.text_field :last_name, class: "form-control custom", placeholder: "", required: "true" %>
        <%= f.label :last_name, class: "form-label" %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <div class="form-floating">
        <%= f.email_field :email, class: "form-control custom", placeholder: "", required: "true" %>
        <%= f.label :email, class: "form-label" %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <div class="form-floating">
        <%= f.password_field :password, class: "form-control custom", minlength: 6, placeholder: "", required: "true" %>
        <%= f.label :password, class: "form-label" %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <div class="form-floating">
        <%= f.password_field :password_confirmation, class: "form-control custom", placeholder: "", required: "true" %>
        <%= f.label :password_confirmation, class: "form-label" %>
      </div>
    </div>
    <br>
    <div class="edit-actions">
      <%= f.submit 'Submit', class: "btn btn-outline-primary accent-color" %>
    </div>
    <% end %>
  </div>
</div>