config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
 
  get 'subscriptions/index'
  get 'subscriptions/new'
  get 'subscriptions/edit'

  get '/about-us', to: 'home#about_us'
  get '/contact', to: 'home#contact'
  get '/meet-our-team', to: 'home#meet_our_team'

  resources :subscriptions, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :edit, :update]

  get '/signup', to: 'users#new'
  get '/users/:user_id', to: 'home#index_logged_in', as: 'user_profile'

  get '/recent_reminders', to: 'reminders#recent_reminders', as: 'recent_reminders'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reminders, dependent: :destroy
  has_many :renewal_dates

  validates :name, presence: true
  validates :cost, presence: true
  validates :frequency, presence: true
  validates :category_id, presence: true
  validates :start_date, presence: true

  def transaction_date
    calculated_date = case frequency
                      when 'Weekly'
                        start_date + ((Date.today - start_date).to_i / 7) * 7
                      when 'Monthly'
                        start_date + ((Date.today.year * 12 + Date.today.month) - (start_date.year * 12 + start_date.month)).months
                      when 'Yearly'
                        start_date + (Date.today.year - start_date.year).years
                      end

    # If the calculated date is in the future, use the last calculated date
    last_calculated_date = calculated_date

    Date.today > calculated_date ? calculated_date : last_calculated_date
  end

  def calculated_renewal_date
    return start_date if start_date.present? && start_date > Date.today

    calculated_date = transaction_date
    today = Date.today

    case frequency
    when 'Weekly'
      # Add 1 week to the transaction date until it's in the future
      calculated_date += 1.week while calculated_date <= today
    when 'Monthly'
      # Add 1 month to the transaction date until it's in the future
      calculated_date += 1.month while calculated_date <= today
    when 'Yearly'
      # Add 1 year to the transaction date until it's in the future
      calculated_date += 1.year while calculated_date <= today
    end

    calculated_date
  end

  def all_renewal_dates
    renewals = []
    current_date = start_date

    case frequency
    when 'Monthly'
      renewals << current_date
      11.times do
        current_date += 1.month
        renewals << current_date
      end
    when 'Yearly'
      renewals << current_date
      1.times do
        current_date += 1.year
        renewals << current_date
      end
    when 'Weekly'
      renewals << current_date
      51.times do # 52 weeks in a year
        current_date += 1.week
        renewals << current_date
      end
    end

    renewals
  end

  after_create :schedule_email_reminder

  def schedule_email_reminder
    return unless calculated_renewal_date == Date.today + 1.day

    EmailReminderService.new(self).send_reminder
  end

  def schedule_email_reminders
    all_renewal_dates.each do |renewal_date|
      ReminderEmailJob.perform_async(id, (renewal_date.to_time.to_i - 1.day.to_i))
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:destroy]
  before_action :require_login
  def index
    @user = current_user
    @subscriptions = @user.subscriptions
  end

  def new
    @subscription = Subscription.new
    @popular_subscriptions = PopularSubscription.all
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.user_id = current_user.id
  
    if @subscription.save
      UserSubscriptionBridge.create(user: current_user, subscription: @subscription)
  
      redirect_to subscriptions_path
    else
      # Handle errors when saving the initial subscription
      redirect_to new_subscription_path
    end
  end
  

  def edit
    @subscription = Subscription.find(params[:id])
  end

  def update
    @subscription = Subscription.find(params[:id])

    if @subscription.update(subscription_params)
      redirect_to subscriptions_path
    else
      render 'edit'
    end
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
    redirect_to subscriptions_path
  end

  private

  def subscription_params
    params.require(:subscription).permit(:name, :cost, :frequency, :renewal_date, :category_id, :start_date)
  end

  def require_login
    return if current_user

    redirect_to '/login'
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/edit.html.erb
<div class="container edit-subscription">
  <br>
  <h1 class="heading">EDIT SUBSCRIPTION</h1>
  <br>
  <%= form_for @subscription do |f| %>
    <% if @subscription.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @subscription.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="edit-form">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control custom" %><br>
      </div>
      <div class="form-group">
        <%= f.label :cost %>
        <%= f.text_field :cost, class: "form-control custom" %><br>
      </div>
      <div class="form-group">
        <%= f.label :frequency %>
        <%= f.select :frequency, %w[Weekly Monthly Yearly], { include_blank: 'Select a Frequency' }, { class: 'form-select custom' } %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :category_id %>
        <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: 'Select a Category' }, { class: 'form-select custom' } %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :subscription_start_date %>
        <%= f.date_field :start_date, class: "form-control custom" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :renewal_date %>
        <%= f.date_field :renewal_date, class: "form-control custom" %>
      </div>
      <br>
      <div class="edit-actions">
        <%= f.submit "Update Subscription", class: "btn btn-outline-primary accent-color" %>
        <%= button_tag t('buttons.cancel'), type: "submit", name: "cancel", value: true, class: "btn btn-outline-danger accent-color" %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/subscriptions/index.html.erb
<%= stylesheet_link_tag 'subscriptions' %>
<%= form_with(model: @subscription, local: true) do |form| %>
  <%= form.hidden_field :authenticity_token, value: form_authenticity_token %>
<% end %>
<div class="container">
    <h2 class="heading">CURRENT SUBSCRIPTIONS</h2>
    <br>
    <table class="table table-hover table-responsive card-body">
      <thead>
        <tr class="table-active table-header">
          <th>Name</th>
          <th>Cost</th>
          <th>Frequency</th>
          <th>Start Date</th>
          <th>Renewal Date</th>
          <th>Category</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="table-group-divider table-body">
        <% @subscriptions.each do |subscription| %>
          <tr>
            <td><%= subscription.name %></td>
            <td>$<%= number_with_precision(subscription.cost, precision: 2) %></td>
            <td><%= subscription.frequency %></td>
            <td><%= subscription.start_date.strftime('%m/%d/%Y') %></td>
            <td><%= subscription.calculated_renewal_date.strftime('%m/%d/%Y') %></td>
            <td><%= subscription.category.name %></td>
            <td>
              <%= link_to(edit_subscription_path(subscription)) do %>
                <div class="btn btn-outline-primary">Edit</div>
              <% end %>
              <%= link_to(subscription, method: :delete, data: { confirm: 'Are you sure?' }) do %>
                <div class="btn btn-outline-danger"> Delete</div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/subscriptions/new.html.erb
<div class="form-popular">
  <div class="new-subscription-form" style="background-image: url('/assets/bckg5.jpg'); background-size: cover; background-repeat: no-repeat; background-attachment: fixed;">
    <h2 class="heading">ADD NEW SUBSCRIPTION</h2>
    <br>
    <%= form_for @subscription do |f| %>
      <% if @subscription.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @subscription.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <br>
      <div class="add-form">
        <div class="form-group">
          <div class="form-floating">
            <%= f.text_field :name, class: "form-control custom", placeholder: "Subscription Service", required: "true" %>
            <%= f.label :name, class: "form-label" %>
          </div>
        </div>
        <br>
        <div class="form-group">
          <div class="form-floating">
            <%= f.text_field :cost, class: "form-control custom", placeholder: "", required: "true" %>
            <%= f.label :cost, class: "form-label" %>
          </div>
        </div>
        <br>
        <div class="form-group">
          <%= f.select :frequency, %w[Weekly Monthly Yearly], { include_blank: 'Select a Frequency' }, { class: 'form-select custom' } %>
        </div>
        <br>
        <div class="form-group">
          <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: 'Select a Category' }, { class: 'form-select custom' } %>
        </div>
        <br>
        <div class="form-group">
          <%= f.date_field :start_date, class: "form-control custom", placeholder: "Start Date of Subscription" %>
        </div>
        <br>
        <div class="edit-actions">
          <%= f.submit "Add", class: "btn btn-outline-primary accent-color" %>
          <a href="<%= user_profile_path(current_user) %>" class="btn btn-outline-danger accent-color" id="cancel-button">Cancel</a>
        </div>
      </div>
    </div>
    <br>
    <div class="popular-subscriptions">
      <h2 class="heading">POPULAR SUBSCRIPTIONS</h2>
      <% @popular_subscriptions.each do |popular_subscription| %>
        <%= link_to popular_subscription.link, target: "_blank" do %>
          <%= image_tag(popular_subscription.logo, class: "images-links") %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
<script>
  document.getElementById('cancel-button').addEventListener('click', function() {
    document.querySelectorAll('.form-control').forEach(function(field) {
      field.removeAttribute('required');
    });
  });
</script>