config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
 
  get 'subscriptions/index'
  get 'subscriptions/new'
  get 'subscriptions/edit'

  get '/about-us', to: 'home#about_us'
  get '/contact', to: 'home#contact'
  get '/meet-our-team', to: 'home#meet_our_team'

  resources :subscriptions, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :edit, :update]

  get '/signup', to: 'users#new'
  get '/users/:user_id', to: 'home#index_logged_in', as: 'user_profile'

  get '/recent_reminders', to: 'reminders#recent_reminders', as: 'recent_reminders'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/_top_nav_bar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Your head content here -->
  </head>

  <body>
    <nav class="top-nav-bar">
      <% if current_user %>
        <%= link_to(user_path(current_user.id)) do %>
          <%= image_tag('RecurrEx-logo.png', alt: 'Recurrex Logo', class: 'logo-image') %>
        <% end %>
        <div class="top-nav-links">
        <div class="nav-item dropdown">
          <div class="nav-link dropdown-toggle" href="#" id="whyRecurrExDropdown" role="button" data-bs-toggle="dropdown">Why RecurrEx?
          </div>
          <div class="dropdown-menu" aria-labelledby="whyRecurrExDropdown">
            <a class="dropdown-item" href="/about-us">About Us</a>
            <a class="dropdown-item" href="/contact">Contact</a>
            <a class="dropdown-item" href="/meet-our-team">Meet Our Team</a>
          </div>
          
        </div>
        <div class="nav-link">
            <%= link_to 'Add Subscription', new_subscription_path %>
          </div>
          <div class="nav-link">
            <%= link_to 'My Subscriptions', subscriptions_path %>
          </div>
          <div class="nav-link">
            <%= link_to 'Reminders', recent_reminders_path %>
          </div>
          <% if current_user %>
            <div class="nav-link">
              <%= link_to 'Edit Profile', edit_user_path(current_user) %>
            </div>
            Signed in as <%= current_user.first_name %> | <%= link_to "Logout", '/logout', class: 'btn btn-outline-primary accent-color'%>
          <% else %>
            <% unless current_page?('/login') %>
              <%= link_to 'Login', '/login', class: 'btn btn-outline-primary accent-color' %> |
            <% end %>
            <% unless current_page?('/signup') %>
              <%= link_to 'Signup', '/signup', class: 'btn btn-outline-primary accent-color'  %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </nav>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag 'rails-ujs' %>
    <%= render 'layouts/top_nav_bar' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= stylesheet_link_tag 'user' %>
    <%= stylesheet_link_tag 'top_nav_bar' %>
    <%= stylesheet_link_tag 'subscriptions' %>
    <%= stylesheet_link_tag 'application' %>
    <%= yield %>
    <script>
      $(document).ready(function() {
      });
      $(document).ready(function() {
        $('#remindersModal').on('show.bs.modal', function(e) {
          $(this).find('.modal-content').load('/reminders/dropdown');
        });
      });
    </script>
    <!-- About link and copyright information -->
    <div class="footer">
      <p>&copy; <%= Time.now.year %> RecurrEx. All rights reserved.</p>
    </div>
  </body>
</html>